version: '2'
services:
  nginx:
    image: nginx
    container_name: "laravel-nginx"
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/src
    links:
      - php

  php:
    build: ./docker/php
    expose:
      - "9000"
    volumes:
      - ./src:/src

  mysql:
     image: mysql
     container_name: "laravel-mysql"
     restart: always
     environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
     ports:
      - 13306:3306
